services:
 
  dbmaster:
    image: mysql:8.0.39
    container_name: redsocialWORKCAST-mysqlMASTER
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
      MYSQL_DATABASE: redsocialworkcast
      MYSQL_USER: UAB
      MYSQL_PASSWORD: 1234
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - monitoring_net
 
  dbSlave:
    image: mysql:8.0.39
    container_name: redsocialWORKCAST-mysqlSLAVE
    depends_on:
      - dbmaster
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=row
    environment: 
      MYSQL_ROOT_PASSWORD: 1234567890
      MYSQL_DATABASE: redsocialworkcast
      MYSQL_USER: UAB
      MYSQL_PASSWORD: 1234
    ports:
      - "3309:3306"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheusWorkcast
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring_net
    healthcheck:
     test: ["CMD", "wget", "--spider", "http://localhost:9090/-/ready"]
     interval: 30s
     timeout: 10s
     retries: 3

  grafana:
    image: grafana/grafana:latest
    container_name: grafanaWorkcast
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin_password
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring_net
 

volumes:
  mysql_data:

networks:
  monitoring_net:
    driver: bridge
  dmz:
