create database mafanike;
use mafanike;

CREATE TABLE usuario (
  id_Perfil int NOT NULL AUTO_INCREMENT,
  Nombre varchar(20) NOT NULL,
  Apellido varchar(20) NOT NULL,
  Correo varchar(40) NOT NULL,
  Contrasena varchar(20) NOT NULL,
  Fecha_Nac date NOT NULL,
  tipo_usuario enum('comun','administrador') NOT NULL,
  PRIMARY KEY (id_Perfil)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE chat (
  ID_CHAT int NOT NULL AUTO_INCREMENT,
  CHAT_GRUPAL tinyint(1) NOT NULL,
  PRIMARY KEY (ID_CHAT)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE ev_grupo (
  ID_EVENTO_GRUPAL int NOT NULL AUTO_INCREMENT,
  ID_EVENTO int NOT NULL,
  PRIMARY KEY (ID_EVENTO_GRUPAL)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE ev_post (
  ID_POST_EV int NOT NULL AUTO_INCREMENT,
  ID_EVENTO int NOT NULL,
  PRIMARY KEY (ID_POST_EV)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE evento (
  ID_EVENTO int NOT NULL AUTO_INCREMENT,
  Nombre varchar(50) NOT NULL,
  Descripcion varchar(255) DEFAULT NULL,
  Fecha date NOT NULL,
  PRIMARY KEY (ID_EVENTO)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE grupo (
  ID_GRUPO int NOT NULL AUTO_INCREMENT,
  Nombre varchar(50) NOT NULL,
  Descripcion varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID_GRUPO)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE ingresa (
  ID_INGRESO int NOT NULL AUTO_INCREMENT,
  ID_GRUPO int NOT NULL,
  ID_PERFIL int NOT NULL,
  PRIMARY KEY (ID_INGRESO),
  FOREIGN KEY (ID_GRUPO) REFERENCES grupo (ID_GRUPO),
  FOREIGN KEY (ID_PERFIL) REFERENCES usuario (id_Perfil)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE likes (
  ID_LIKE int NOT NULL AUTO_INCREMENT,
  ID_PERFIL int NOT NULL,
  ID_POST int NOT NULL,
  PRIMARY KEY (ID_LIKE),
  FOREIGN KEY (ID_PERFIL) REFERENCES usuario (id_Perfil)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE post (
  ID_POST int NOT NULL AUTO_INCREMENT,
  ID_PERFIL int NOT NULL,
  Contenido varchar(255) NOT NULL,
  PRIMARY KEY (ID_POST),
  FOREIGN KEY (ID_PERFIL) REFERENCES usuario (id_Perfil)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE post_imagen (
  ID_IMAGEN int NOT NULL AUTO_INCREMENT,
  ID_POST int NOT NULL,
  URL varchar(255) NOT NULL,
  PRIMARY KEY (ID_IMAGEN),
  FOREIGN KEY (ID_POST) REFERENCES post (ID_POST)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE post_link (
  ID_LINK int NOT NULL AUTO_INCREMENT,
  ID_POST int NOT NULL,
  URL varchar(255) NOT NULL,
  PRIMARY KEY (ID_LINK),
  FOREIGN KEY (ID_POST) REFERENCES post (ID_POST)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE post_texto (
  ID_TEXTO int NOT NULL AUTO_INCREMENT,
  ID_POST int NOT NULL,
  TEXTO varchar(255) NOT NULL,
  PRIMARY KEY (ID_TEXTO),
  FOREIGN KEY (ID_POST) REFERENCES post (ID_POST)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE mensaje (
  ID_MENSAJE int NOT NULL AUTO_INCREMENT,
  ID_CHAT int NOT NULL,
  ID_PERFIL int NOT NULL,
  Contenido varchar(255) NOT NULL,
  PRIMARY KEY (ID_MENSAJE),
  FOREIGN KEY (ID_CHAT) REFERENCES chat (ID_CHAT),
  FOREIGN KEY (ID_PERFIL) REFERENCES usuario (id_Perfil)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE mensaje_imagen (
  ID_IMAGEN int NOT NULL AUTO_INCREMENT,
  ID_MENSAJE int NOT NULL,
  URL varchar(255) NOT NULL,
  PRIMARY KEY (ID_IMAGEN),
  FOREIGN KEY (ID_MENSAJE) REFERENCES mensaje (ID_MENSAJE)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE mensaje_texto (
  ID_TEXTO int NOT NULL AUTO_INCREMENT,
  ID_MENSAJE int NOT NULL,
  TEXTO varchar(255) NOT NULL,
  PRIMARY KEY (ID_TEXTO),
  FOREIGN KEY (ID_MENSAJE) REFERENCES mensaje (ID_MENSAJE)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE videollamada (
  ID_VIDEOLLAMADA int NOT NULL AUTO_INCREMENT,
  ID_CHAT int NOT NULL,
  PRIMARY KEY (ID_VIDEOLLAMADA),
  FOREIGN KEY (ID_CHAT) REFERENCES chat (ID_CHAT)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE telefono (
  ID_TELEFONO int NOT NULL AUTO_INCREMENT,
  ID_PERFIL int NOT NULL,
  NUMERO varchar(20) NOT NULL,
  PRIMARY KEY (ID_TELEFONO),
  FOREIGN KEY (ID_PERFIL) REFERENCES usuario (id_Perfil)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE tema (
  ID_TEMA int NOT NULL AUTO_INCREMENT,
  NOMBRE_TEMA varchar(50) NOT NULL,
  PRIMARY KEY (ID_TEMA)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE une_vid (
  ID_VIDEOLLAMADA int NOT NULL,
  ID_PERFIL int NOT NULL,
  PRIMARY KEY (ID_VIDEOLLAMADA, ID_PERFIL),
  FOREIGN KEY (ID_VIDEOLLAMADA) REFERENCES videollamada (ID_VIDEOLLAMADA),
  FOREIGN KEY (ID_PERFIL) REFERENCES usuario (id_Perfil)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE upvote_pt (
  ID_UPVOTE_PT int NOT NULL AUTO_INCREMENT,
  ID_PERFIL int NOT NULL,
  ID_TEXTO int NOT NULL,
  PRIMARY KEY (ID_UPVOTE_PT),
  FOREIGN KEY (ID_PERFIL) REFERENCES usuario (id_Perfil),
  FOREIGN KEY (ID_TEXTO) REFERENCES post_texto (ID_TEXTO)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE upvote_up (
  ID_UPVOTE_UP int NOT NULL AUTO_INCREMENT,
  ID_PERFIL int NOT NULL,
  ID_POST int NOT NULL,
  PRIMARY KEY (ID_UPVOTE_UP),
  FOREIGN KEY (ID_PERFIL) REFERENCES usuario (id_Perfil),
  FOREIGN KEY (ID_POST) REFERENCES post (ID_POST)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE upvote_ut (
  ID_UPVOTE_UT int NOT NULL AUTO_INCREMENT,
  ID_PERFIL int NOT NULL,
  ID_TEMA int NOT NULL,
  PRIMARY KEY (ID_UPVOTE_UT),
  FOREIGN KEY (ID_PERFIL) REFERENCES usuario (id_Perfil),
  FOREIGN KEY (ID_TEMA) REFERENCES tema (ID_TEMA)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


